// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DemoService is the Go half of demo mode: hands the parsed script to the
 * frontend player once it asks, and records the window with macOS's own
 * screencapture while the script says so. One recording at a time.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Fullscreen puts the window into macOS full screen and returns once it is
 * there. The transition is animated, and `record` measures the window's
 * bounds when it starts, so returning at once would record the rectangle
 * the window was leaving. Polled rather than observed: the window's own
 * state is what the recorder will read, so it is what is waited for.
 */
export function Fullscreen(): $CancellablePromise<void> {
    return $Call.ByID(654977979);
}

/**
 * Script returns the steps of the script named by HERMES_DEMO, nil when it
 * is unset, or the first line that could not be read.
 */
export function Script(): $CancellablePromise<$models.DemoStep[] | null> {
    return $Call.ByID(2377728253);
}

/**
 * StartRecording begins recording the window to path.
 */
export function StartRecording(path: string): $CancellablePromise<void> {
    return $Call.ByID(1378549741, path);
}

/**
 * StopRecording interrupts the recorder and waits for it to close the file.
 */
export function StopRecording(): $CancellablePromise<void> {
    return $Call.ByID(2065169397);
}
