// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearRecents(): $CancellablePromise<void> {
    return $Call.ByID(3493938995);
}

export function ExportPDF(): $CancellablePromise<void> {
    return $Call.ByID(2450231792);
}

export function IsDirty(): $CancellablePromise<boolean> {
    return $Call.ByID(410112692);
}

export function Open(): $CancellablePromise<$models.Document> {
    return $Call.ByID(4179904212);
}

export function OpenPath(path: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(3640861155, path);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2527160883);
}

export function RecentFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3158636934);
}

export function Save(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(494444433, path, content);
}

export function SaveAs(content: string): $CancellablePromise<string> {
    return $Call.ByID(1161953465, content);
}

export function SetDirty(dirty: boolean): $CancellablePromise<void> {
    return $Call.ByID(2193338676, dirty);
}
