// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ChooseBibliography is the open panel behind "an existing file" in the New
 * Document flow. It returns "" when the author cancels, so the caller can
 * tell a cancel from an error, as ChooseNewDocumentPath does.
 */
export function ChooseBibliography(): $CancellablePromise<string> {
    return $Call.ByID(1637356601);
}

/**
 * ChooseNewDocumentPath asks where a new document should live. It is the
 * first half of File → New…: the frontend needs the chosen name before it can
 * compose the document, because the live `bibliography:` key names a `.bib`
 * after the document's own stem. Empty when the panel is cancelled.
 * 
 * The panel's own "Replace?" prompt is what guards an existing `.md`; nothing
 * here checks for one.
 */
export function ChooseNewDocumentPath(): $CancellablePromise<string> {
    return $Call.ByID(3379613135);
}

export function ClearRecents(): $CancellablePromise<void> {
    return $Call.ByID(3493938995);
}

/**
 * CreateDocument is the second half: it writes the document, and — when
 * bibName is set — a bibliography beside it, resolved the same way a
 * `bibliography:` key is. A bibliography that already exists is left exactly
 * as it is: a library beside the chosen name is what the author wants to
 * point at, not something to replace with a seed. Only bibContent's write is
 * conditional; the document itself is always written, since the save panel
 * has already confirmed any replacement.
 * 
 * Split from the dialog so it is testable without one, the same reason
 * feedbackURL and quitRequest are separate from what calls them.
 */
export function CreateDocument(path: string, content: string, bibName: string, bibContent: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(839519561, path, content, bibName, bibContent);
}

export function DiscardDraft(docPath: string): $CancellablePromise<void> {
    return $Call.ByID(607038005, docPath);
}

/**
 * ExportPDF asks for a destination and renders the document there with no
 * print panel. The panel is deliberately not used: paper size is a setting
 * now, because the preview draws the sheet at that size, and the panel's own
 * paper picker would be a second source of truth for the same fact — a user
 * who changed it there would get a PDF whose measure did not match the sheet
 * they wrote against.
 */
export function ExportPDF(docPath: string): $CancellablePromise<void> {
    return $Call.ByID(2450231792, docPath);
}

/**
 * ImportData opens a native picker for a delimited data file and returns its
 * contents. The reading half is split into readDataFile so it stays testable,
 * the same way ReadBibliography is testable while Open is not.
 */
export function ImportData(): $CancellablePromise<string> {
    return $Call.ByID(2788725769);
}

export function IsDirty(): $CancellablePromise<boolean> {
    return $Call.ByID(410112692);
}

export function Open(): $CancellablePromise<$models.Document> {
    return $Call.ByID(4179904212);
}

export function OpenPath(path: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(3640861155, path);
}

/**
 * PickCitations opens Zotero's citation picker via Better BibTeX's CAYW
 * endpoint and returns the chosen citations in Pandoc format. The timeout is
 * long because the user is interacting with the picker; an empty response
 * means they cancelled.
 */
export function PickCitations(): $CancellablePromise<string> {
    return $Call.ByID(873413501);
}

/**
 * PrintDocument opens the system print panel. Picking a printer and a tray is
 * a job the panel is genuinely good at; picking paper is not, which is why
 * export no longer goes through here.
 */
export function PrintDocument(): $CancellablePromise<void> {
    return $Call.ByID(2407220630);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2527160883);
}

export function ReadBibliography(path: string, docPath: string): $CancellablePromise<string> {
    return $Call.ByID(3582225424, path, docPath);
}

/**
 * RecentFiles takes no lock: the list is written atomically, so a concurrent
 * update is either fully visible or not visible at all — there is no partial
 * state on disk to read. Only the read-modify-write in addRecent needs
 * serialising, and it uses readRecents directly to avoid re-entering the lock.
 */
export function RecentFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3158636934);
}

export function RecoverDraft(docPath: string): $CancellablePromise<$models.Draft> {
    return $Call.ByID(2854644563, docPath);
}

export function Save(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(494444433, path, content);
}

export function SaveAs(content: string): $CancellablePromise<string> {
    return $Call.ByID(1161953465, content);
}

export function SetDirty(dirty: boolean): $CancellablePromise<void> {
    return $Call.ByID(2193338676, dirty);
}

/**
 * Settings returns every persisted preference. Values are always valid: a
 * missing or malformed file, and any field outside its allowed set, read back
 * as that field's default.
 */
export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3490222329);
}

/**
 * UpdateSettings persists the given preferences and returns an error if they
 * could not be written, so a caller can tell the user the choice did not
 * stick. Out-of-range values are normalised rather than rejected.
 */
export function UpdateSettings(next: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2788627576, next);
}

/**
 * WatchBibliography (re)arms the single bibliography watcher. An empty path
 * stops watching. The goroutine polls mtime+size and notifies on change; a
 * missing file keeps polling and notifies when it appears.
 */
export function WatchBibliography(path: string, docPath: string): $CancellablePromise<void> {
    return $Call.ByID(3958672815, path, docPath);
}

/**
 * WriteDraft, DiscardDraft and RecoverDraft are the recovery-draft bindings.
 * The frontend decides *when* (lib/recoveryDraft.ts: debounced while dirty,
 * discarded on the dirty-to-clean transition); the store decides whether a
 * draft is still worth offering. See recovery.go.
 */
export function WriteDraft(docPath: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(1661680238, docPath, content);
}
