// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearRecents(): $CancellablePromise<void> {
    return $Call.ByID(3493938995);
}

export function ExportPDF(): $CancellablePromise<void> {
    return $Call.ByID(2450231792);
}

export function IsDirty(): $CancellablePromise<boolean> {
    return $Call.ByID(410112692);
}

export function Open(): $CancellablePromise<$models.Document> {
    return $Call.ByID(4179904212);
}

export function OpenPath(path: string): $CancellablePromise<$models.Document> {
    return $Call.ByID(3640861155, path);
}

/**
 * PickCitations opens Zotero's citation picker via Better BibTeX's CAYW
 * endpoint and returns the chosen citations in Pandoc format. The timeout is
 * long because the user is interacting with the picker; an empty response
 * means they cancelled.
 */
export function PickCitations(): $CancellablePromise<string> {
    return $Call.ByID(873413501);
}

export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(2527160883);
}

export function ReadBibliography(path: string, docPath: string): $CancellablePromise<string> {
    return $Call.ByID(3582225424, path, docPath);
}

/**
 * RecentFiles takes no lock: the list is written atomically, so a concurrent
 * update is either fully visible or not visible at all — there is no partial
 * state on disk to read. Only the read-modify-write in addRecent needs
 * serialising, and it uses readRecents directly to avoid re-entering the lock.
 */
export function RecentFiles(): $CancellablePromise<string[] | null> {
    return $Call.ByID(3158636934);
}

export function Save(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(494444433, path, content);
}

export function SaveAs(content: string): $CancellablePromise<string> {
    return $Call.ByID(1161953465, content);
}

export function SetDirty(dirty: boolean): $CancellablePromise<void> {
    return $Call.ByID(2193338676, dirty);
}

/**
 * Settings returns every persisted preference. Values are always valid: a
 * missing or malformed file, and any field outside its allowed set, read back
 * as that field's default.
 */
export function Settings(): $CancellablePromise<$models.Settings> {
    return $Call.ByID(3490222329);
}

/**
 * UpdateSettings persists the given preferences and returns an error if they
 * could not be written, so a caller can tell the user the choice did not
 * stick. Out-of-range values are normalised rather than rejected.
 */
export function UpdateSettings(next: $models.Settings): $CancellablePromise<void> {
    return $Call.ByID(2788627576, next);
}

/**
 * WatchBibliography (re)arms the single bibliography watcher. An empty path
 * stops watching. The goroutine polls mtime+size and notifies on change; a
 * missing file keeps polling and notifies when it appears.
 */
export function WatchBibliography(path: string, docPath: string): $CancellablePromise<void> {
    return $Call.ByID(3958672815, path, docPath);
}
