// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

import * as DemoService from "./demoservice.js";
import * as DocumentService from "./documentservice.js";
export {
    DemoService,
    DocumentService
};

export type {
    DemoStep,
    Document,
    Draft,
    Settings,
    UpdateResult
} from "./models.js";
