// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Document {
    "path": string;
    "content": string;
}

/**
 * Draft is what RecoverDraft hands the frontend. Found false means there is
 * nothing worth offering: no draft, or one the document on disk has caught
 * up with. Content is the draft's full text.
 */
export interface Draft {
    "found": boolean;
    "content": string;
}

/**
 * Settings holds every persisted user preference in one value. Adding a
 * preference means adding a field with a json tag, a default in
 * defaultSettings, and a clamp in normalise — persistence, change
 * notification, the menu rebuild, and the frontend binding all follow with no
 * further wiring.
 */
export interface Settings {
    "printOrientation": string;
    "syncScrolling": boolean;
    "theme": string;
    "figureAlignment": string;
    "chartWidth": string;
    "paperSize": string;
    "showOutline": boolean;

    /**
     * Writes a recovery draft while the document is dirty. See recovery.go.
     */
    "autoSave": boolean;

    /**
     * Whether Hermes may fetch the version feed: "unasked" until the first
     * launch has put the question, then "on" or "off". See update.go.
     */
    "updateCheck": string;
}

/**
 * UpdateResult is what CheckForUpdates hands the frontend. Checked false
 * means the throttle applied and nothing was fetched; Current is filled
 * either way so a manual "up to date" message can name the version.
 */
export interface UpdateResult {
    "checked": boolean;
    "available": boolean;
    "current": string;
    "latest": string;
    "url": string;
}
